name: wave_mobile_money
version: "1.0.0"
config-version: 2

profile: wave_mobile_money

model-paths: ["models"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  incremental_lookback_hours: 3

models:
  wave_mobile_money:
    staging:
      +schema: staging
      +materialized: view
      +tags: ["every_15m"]
    intermediate:
      +schema: intermediate
      +materialized: table
      +tags: ["every_15m"]
    marts:
      core:
        +schema: core
        +materialized: table
        +tags: ["every_15m"]
      kpi:
        +schema: kpi
        +materialized: table
        +tags: ["hourly"]
      compliance:
        +schema: compliance
        +tags: ["every_15m"]
